model:
  name: "FruitClassifier"
  type: "NeuralNetwork"
  parameters:
    input_size: 3
    hidden_size: 4
    output_size: 1
    learning_rate: 0.01
    activation: "relu"

training:
  epochs: 1000
  batch_size: 4
  validation_split: 0.2

data:
  csv_path: "data/raw/fruits.csv"
  features: ["sweetness", "crunchiness", "redness"]
  target: "label"
